# -*- coding: utf-8 -*-
"""pcmb_singletest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urXl2-gmGYqgbO1TLyoxwDn3Xdl9BEJ5
"""

import pickle

import tensorflow as tf
#from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
model=tf.keras.models.load_model('pcmb20_model.h5')
with open('tokenizer20.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

def prepare_question(text):
  text=text.replace('\n',' ')
#  vocab_size = 1000
#  oov_token = '<oov>'
  trunc='post'
  maxlen = 50
#  embedded_dim = 8
  # tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_token)
  # tokenizer.fit_on_texts([text])
  # word_index = tokenizer.word_index
  sequences = tokenizer.texts_to_sequences([text])
  return pad_sequences(sequences, maxlen=maxlen, truncating=trunc)


def pcmb_classify(test_string):
    input=prepare_question(test_string)
    a=model.predict([input]).tolist()[0]
    #print(a)
    max_val=max(a)
    max_index=a.index(max_val)

    subjects={
            0:'Biology',
            1:'Chemistry',
            2:'Maths',
            3:'Physics'
            }

    prediction=subjects[max_index]
    return prediction

test_string=""" 
(i) A constant electric field in the z-direction.
(ii) A field that uniformly increase in magnitude but its direction remains unchanged along the """

print(pcmb_classify(test_string))